import {useEffect,useState} from 'react';
import {Box,ChevronRight,Download,FileImage,Film,FolderOpen,GitBranch,ImagePlus,Layers3,Library,Play,Plus,Settings,ShieldCheck,Sparkles,Zap} from 'lucide-react';
import {EventsOn} from '../wailsjs/runtime/runtime';
import CharacterViewport from './CharacterViewport';

type Stage={id:string,name:string,status:string,detail:string};type Artifact={stage:string,kind:string,path:string,metrics?:Record<string,unknown>};type Log={time:string,stage:string,level:string,message:string};type Job={id:string,name:string,created:string,status:string,progress:number,image?:string,imageHash?:string,workspace?:string,stages:Stage[],artifacts?:Artifact[],logs?:Log[]};
const api=()=> (window as any).go?.main?.App;
const initial:Job={id:'demo',name:'Import a character to begin',created:new Date().toISOString(),status:'draft',progress:0,stages:[{id:'prepare',name:'Image cleanup',status:'ready',detail:'Background removal & subject validation'},{id:'reconstruct',name:'3D reconstruction',status:'queued',detail:'TripoSR / InstantMesh adapter'},{id:'retopo',name:'Mesh cleanup',status:'queued',detail:'Retopology, UV & materials'},{id:'rig',name:'Auto rig',status:'queued',detail:'Skeleton & skin weights'},{id:'motion',name:'Animation',status:'queued',detail:'Motion retargeting'},{id:'export',name:'Export',status:'queued',detail:'GLB / FBX / USDZ'}]};
const motions=['Idle breathing','Confident walk','Run cycle','Friendly wave','Combat stance'];
function App(){const[jobs,setJobs]=useState<Job[]>([initial]);const[selected,setSelected]=useState('demo');const[tab,setTab]=useState('Create');const[motion,setMotion]=useState(false);const[notice,setNotice]=useState('');const[running,setRunning]=useState(false);const[workerMessage,setWorkerMessage]=useState('');const job=jobs.find(j=>j.id===selected)||jobs[0];
useEffect(()=>{api()?.ListJobs().then((x:Job[])=>{if(x?.length){setJobs(x);setSelected(x[0].id)}}).catch(()=>{});const off=EventsOn('worker:event',(event:any)=>{if(event?.message)setWorkerMessage(event.message)});return()=>off()},[]);
async function importImage(){try{const j=await api()?.ImportReference();if(j){setJobs(v=>[j,...v.filter(x=>x.id!==j.id&&x.id!=='demo')]);setSelected(j.id);setNotice('Reference copied with SHA-256 provenance.')}}catch(e){if(!String(e).includes('cancelled'))setNotice(String(e))}}
async function advance(){if(job.id==='demo'){setNotice('Import a reference image before running the pipeline.');return}setRunning(true);setWorkerMessage('Starting isolated worker…');try{const j=await api()?.RunNextStage(job.id);if(j)setJobs(v=>v.map(x=>x.id===j.id?j:x));setNotice('Stage completed and artifact provenance was recorded.')}catch(e){setNotice(String(e))}finally{setRunning(false);setWorkerMessage('')}}
async function openWorkspace(){if(job.id==='demo'){setNotice('Import a project to open its workspace.');return}try{await api()?.OpenWorkspace(job.id)}catch(e){setNotice(String(e))}}
const activeTab=tab==='Assets'?'Assets':tab==='Versions'?'Versions':'Pipeline';
return <div className="shell"><aside><div className="brand"><div className="mark"><Sparkles/></div><div><b>SPRITEENGINE</b><span>AI CHARACTER STUDIO</span></div></div><nav>{[['Create',ImagePlus],['Projects',Library],['Motion Lab',Film],['Export',Download]].map(([n,I]:any)=><button key={n} className={tab===n?'active':''} onClick={()=>setTab(n)}><I/>{n}</button>)}</nav><div className="aside-bottom"><button><Settings/>Settings</button><div className="compute"><span><i/> Local compute</span><small>Python worker · {running?'Busy':'Ready'}</small></div></div></aside>
<main><header><div><span className="eyebrow">WORKSPACE / {tab.toUpperCase()}</span><h1>Turn one image into a living character.</h1></div><div className="header-actions"><button onClick={()=>setNotice('Research: docs/RESEARCH.md · Architecture: docs/ARCHITECTURE.md')}><GitBranch/>Research library</button><button className="primary" onClick={importImage}><Plus/>Import character</button></div></header>
<section className="content">{notice&&<button className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></button>}<div className="toolbar"><div className="tabs">{['Pipeline','Assets','Versions'].map(x=><button key={x} className={activeTab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="status"><i/> Engine {running?'working':'ready'} <span>v0.3 worker pipeline</span></div></div>
<div className="workspace"><div className="viewport"><div className="viewtop"><span>INTERACTIVE SCENE · DRAG TO ORBIT</span><div><button>Perspective</button><button>Lit</button></div></div><CharacterViewport animated={motion}/><div className="axis"><b>Y</b><span>X</span><em>Z</em></div><div className="scene-note"><Box/><div><b>Rig preview</b><span>OrbitControls · procedural humanoid</span></div></div></div>
<div className="inspector"><div className="ins-head"><div><span>ACTIVE PROJECT</span><h2>{job.name}</h2></div><button>•••</button></div>{job.imageHash&&<div className="provenance">SOURCE VERIFIED <b>{job.imageHash.slice(0,12)}</b></div>}<div className="progress"><div><span>{workerMessage||'Pipeline progress'}</span><b>{job.progress}%</b></div><i><em className={running?'indeterminate':''} style={{width:`${job.progress}%`}}/></i></div><div className="steps">{job.stages.map((s,i)=><div className={`step ${s.status}`} key={s.id}><div className="stepnum">{s.status==='done'?'✓':s.status==='running'?'··':i+1}</div><div><b>{s.name}</b><span>{s.detail}</span></div><ChevronRight/></div>)}</div><button className="run" disabled={running||job.status==='complete'} onClick={advance}><Zap/>{running?'Worker running…':job.status==='complete'?'Pipeline complete':'Run next stage'}</button><p className="hint"><ShieldCheck/> Every stage is non-destructive and versioned.</p></div></div>
<div className="bottom"><div className="asset-head"><div><span>PROJECT ASSETS</span><b>Recent generations</b></div><button onClick={openWorkspace}><FolderOpen/> Open workspace</button></div><div className="cards">{jobs.slice(0,3).map((j,i)=><button key={j.id} className={`card ${selected===j.id?'chosen':''}`} onClick={()=>setSelected(j.id)}><div className={`thumb t${i}`}><Layers3/><span>{j.progress}%</span></div><b>{j.name}</b><small>{j.status} · {j.artifacts?.length||0} artifacts</small></button>)}<button className="upload" onClick={importImage}><div><FileImage/><Plus/></div><b>Import reference image</b><small>PNG, JPG, WEBP · immutable workspace copy</small></button></div>{job.logs?.length?<div className="pipeline-log"><b>PIPELINE LOG</b>{job.logs.slice(-4).map((x,i)=><span key={i}><em>{x.stage}</em>{x.message}</span>)}</div>:null}<div className="motionbar"><div><Play/><span><b>Motion quick test</b><small>Preview procedural rig animation</small></span></div><select>{motions.map(x=><option key={x}>{x}</option>)}</select><button className={motion?'playing':''} onClick={()=>setMotion(x=>!x)}>{motion?'Stop preview':'Play preview'} <ChevronRight/></button></div></div>
</section></main></div>}
export default App;
