// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdvanceJob(arg1:string):Promise<main.Job>;

export function CreateJob(arg1:string):Promise<main.Job>;

export function ImportReference():Promise<main.Job>;

export function ListJobs():Promise<Array<main.Job>>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function RunNextStage(arg1:string):Promise<main.Job>;

export function SystemInfo():Promise<main.SystemInfo>;
