// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdvanceJob(arg1:string):Promise<main.Job>;

export function ClearRunPodConfig():Promise<main.RunPodConfig>;

export function CreateJob(arg1:string):Promise<main.Job>;

export function DeleteJob(arg1:string):Promise<Array<main.Job>>;

export function ExportFinalGLB(arg1:string):Promise<string>;

export function GetRunPodConfig():Promise<main.RunPodConfig>;

export function ImportReference():Promise<main.Job>;

export function ImportReferenceData(arg1:string,arg2:string):Promise<main.Job>;

export function ListJobs():Promise<Array<main.Job>>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function ReadArtifact(arg1:string):Promise<string>;

export function ReadJobImage(arg1:string):Promise<string>;

export function RenameJob(arg1:string,arg2:string):Promise<main.Job>;

export function ResetStage(arg1:string,arg2:string):Promise<main.Job>;

export function RunAllStages(arg1:string):Promise<main.Job>;

export function RunNextStage(arg1:string):Promise<main.Job>;

export function RunPodGenerateMotion(arg1:string,arg2:Array<main.MotionPrompt>):Promise<main.MotionGenerateResult>;

export function SaveAndTestRunPodConfig(arg1:string,arg2:string,arg3:string):Promise<main.RunPodStatus>;

export function SaveAnimatedGLB(arg1:string,arg2:string):Promise<string>;

export function SaveRunPodConfig(arg1:string,arg2:string,arg3:string):Promise<main.RunPodConfig>;

export function SystemInfo():Promise<main.SystemInfo>;

export function TestRunPod():Promise<main.RunPodStatus>;
