// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvanceJob(arg1) {
  return window['go']['main']['App']['AdvanceJob'](arg1);
}

export function ClearRunPodConfig() {
  return window['go']['main']['App']['ClearRunPodConfig']();
}

export function CreateJob(arg1) {
  return window['go']['main']['App']['CreateJob'](arg1);
}

export function GetRunPodConfig() {
  return window['go']['main']['App']['GetRunPodConfig']();
}

export function ImportReference() {
  return window['go']['main']['App']['ImportReference']();
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadArtifact(arg1) {
  return window['go']['main']['App']['ReadArtifact'](arg1);
}

export function RunAllStages(arg1) {
  return window['go']['main']['App']['RunAllStages'](arg1);
}

export function RunNextStage(arg1) {
  return window['go']['main']['App']['RunNextStage'](arg1);
}

export function SaveAndTestRunPodConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAndTestRunPodConfig'](arg1, arg2, arg3);
}

export function SaveRunPodConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRunPodConfig'](arg1, arg2, arg3);
}

export function SystemInfo() {
  return window['go']['main']['App']['SystemInfo']();
}

export function TestRunPod() {
  return window['go']['main']['App']['TestRunPod']();
}
